### ISSUE TITLE
Stroke is not fully opaque

### ISSUE THREAD

**Issue by ni554n** [mukeshsolanki/DrawingView-Android#10]
## Changing **Color.RED** with `setAlpha(int)` doesn't seem to have any effect. This is how the stroke looks on bright background.

![screenshot_20170819221253](https://user-images.githubusercontent.com/2310552/29498934-b1880232-8627-11e7-8aa4-9747e35afbcc.png)

**Comment by mukeshsolanki** [comment]
can you share your code?

**Comment by abedham** [comment]
@mukeshsolanki you can see my pull request which solve the problem :+1:

**Comment by mukeshsolanki** [comment]
set alpha is not supported because if you don't want to draw anything why use the library.
