### ISSUE TITLE
Color picker issue

### ISSUE THREAD

**Issue by HDebeuf** [mukeshsolanki/DrawingView-Android#14]
Hi,
Your DrawingView repository is really amazing and helps a lot for the development of an educative app for children where I'm completing an internship.
I was just wondering if it is normal that when you chose another colour while drawing, a white overlay overrides the colour line.
This happens only when the pen is moving. So when you just tap with the pen the colour is correctly used.
On the screenshot:
1. Regular pen without colour picked
2. Color picked and draw a line
3. Color picked and tapped simple dots

![screenshot_20180408-122236](https://user-images.githubusercontent.com/32390605/38466333-07b04452-3b28-11e8-8ba8-9f7687116499.png)

May you help me with this issue?
Kind regards,
Hendrik

**Comment by HDebeuf** [comment]
Hi,

Finally, I figured out how to resolve this, simply by changing the PorterDuff.Mode in the Drawing View to SRC_OVER.

Kind regards,
Hendrik

**Comment by rajgar114** [comment]
Can you please explain in detail where and how to set Mode to SRC_OVER. I have tried to change it in xml file like:-

  <com.mukesh.DrawingView
        android:id="@+id/scratch_pad"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/buttons"
        android:foregroundTintMode="src_over"
        android:backgroundTintMode="src_over"
        />

But it didn't worked for me. Thanks in advance.

**Comment by HDebeuf** [comment]
Dear mukeshsolanki,


This is not situated in the xml file, but rather in the DrawingView class.
You can see my code attached, but briefly, I’ve Overrided the onTouchEvent and edited initialiseEraser as follow:
@Override public boolean onTouchEvent(MotionEvent event) {
    float x = event.getX();
    float y = event.getY();
    switch (event.getAction()) {
        case MotionEvent.ACTION_DOWN:
            if (!mDrawMode) {
                mPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));
            } else {
                mPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));
            }
            touch_start(x, y);
            invalidate();
            break;
        case MotionEvent.ACTION_MOVE:
            touch_move(x, y);
            if (!mDrawMode) {
                mPath.lineTo(mX, mY);
                mPath.reset();
                mPath.moveTo(x, y);
            }
            mCanvas.drawPath(mPath, mPaint);
            invalidate();
            break;
        case MotionEvent.ACTION_UP:
            touch_up();
            invalidate();
            break;
    }
    return true;
}

public void initializeEraser() {
    mDrawMode = false;
    mPaint.setColor(Color.parseColor("#FAFAFA"));
    mPaint.setStyle(Paint.Style.STROKE);
    mPaint.setStrokeWidth(mEraserSize);
    mPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));
}

Kind regards


  
Hendrik Debeuf 

IT Business Analyst

IT Syst. Arch. Student, H.D. Invest sprl



m:
+32 479 59 02 44

a:
3, Rue de la légère eau 
1420, Braine-l'alleud, Belgium

w:
hdinvest.xyz
  e: hendrik@hdinvest.xyz
